"""Pydantic request/response models for the Clinical Evidence Synthesizer API."""

from pydantic import BaseModel, Field
from typing import List, Optional


class QueryRequest(BaseModel):
    """Request model for a single evidence query."""
    query: str = Field(..., description="The clinical question to ask")


class CompareRequest(BaseModel):
    """Request model for comparing two drugs."""
    drug_a: str = Field(..., description="Name of the first drug")
    drug_b: str = Field(..., description="Name of the second drug")


class SourceCitation(BaseModel):
    """A single source citation with document name, page, and content snippet."""
    document: str = Field(..., description="Filename of the source document")
    page: int = Field(..., description="Page number where the evidence appears")
    content: str = Field(..., description="Excerpt of the relevant content")


class QueryResponse(BaseModel):
    """Response model for a single evidence query."""
    answer: str = Field(..., description="The answer generated by the AI agent")
    sources: List[SourceCitation] = Field(
        default_factory=list,
        description="List of source citations supporting the answer"
    )


class CompareResponse(BaseModel):
    """Response model for a drug comparison query."""
    drug_a: str = Field(..., description="Name of the first drug")
    drug_b: str = Field(..., description="Name of the second drug")
    comparison: str = Field(..., description="Structured comparison text")
    sources: List[SourceCitation] = Field(
        default_factory=list,
        description="List of source citations supporting the comparison"
    )


class DocumentInfo(BaseModel):
    """Information about an uploaded document."""
    filename: str = Field(..., description="Name of the uploaded PDF file")
    chunks: int = Field(..., description="Number of chunks indexed from this document")


class UploadResponse(BaseModel):
    """Response after a successful PDF upload."""
    status: str = Field(..., description="Status of the upload operation")
    filename: str = Field(..., description="Name of the uploaded file")
    chunks: int = Field(..., description="Number of chunks created and indexed")
